### ISSUE TITLE
Sheets API includes Egypt as an Asian country but not Russia

### ISSUE THREAD

**Issue by KilimAnnejaro** [datacommonsorg/docsite#142]
When running the command `=DCPLACESIN(A1, "Country")` (where A1 = `asia` as a DCID) and then `=DCGETNAME(B1)` on the output, the list of names output includes Egypt but not Russia. This strikes me as a little strange.

**Comment by beets** [comment]
Egypt is listed in both Asia and Africa, Russia is in both Asia and Europe.
DCPLACESIN should return them in both continents.

**Comment by KilimAnnejaro** [comment]
Update: https://docs.google.com/spreadsheets/d/1e7EJQQD3Lm7wifWpilGZBNcIeD-CLMlrFNLil9AhnB8/edit?usp=sharing
I just tried this again. It is now returning both Egypt and Russia as countries in Asia, but also including the USSR as a country in Asia.

**Comment by beets** [comment]
This should be fixed now!
