### ISSUE TITLE
docs.datacommons.org/tutorials.html 404

### ISSUE THREAD

**Issue by danbri** [datacommonsorg/docsite#166]
From the site-wide Documentation toolbar - 

https://github.com/datacommonsorg/docsite/blob/02d6a469019c645365533ab8ba873b679d204497/_layouts/default.html#L53

* https://docs.datacommons.org/tutorials.html is 404 currently.
* https://docs.datacommons.org/tutorials/ seems to work.

**Comment by enjoythecode** [comment]
this was fixed with #174

**Comment by beets** [comment]
thanks for pointing that out!
