### ISSUE TITLE
[v1-rest] Maintain old v0 API links

### ISSUE THREAD

**Issue by beets** [datacommonsorg/docsite#249]
Since we have published links to our v0 API (which could be bookmarked, etc), please maintain the old link structure, or add redirects.

https://docs.datacommons.org/api/rest/place_in.html -- content
https://juliawu.github.io/datacommons-docsite/api/rest/place_in.html -- 404

Suggested fix: move old files back to the existing, prod, structure (so first link above continues to work)

As a follow on when we are ready to deprecate v0, we can move to a v0 subfolder with redirects & pointers to the new versions of the API.

**Comment by juliawu** [comment]
I believe the current master branch upholds this, but the demo-site does not (I've been testing things in the background). Plan is definitely to maintain current links until at least v0 is officially depreciated. Demo-site has been updated to reflect intended structure (https://juliawu.github.io/datacommons-docsite/api/rest/place_in.html should work now.)
