### ISSUE TITLE
[v1-rest observations/series] note what preferred facet means

### ISSUE THREAD

**Issue by beets** [datacommonsorg/docsite#253]
https://juliawu.github.io/datacommons-docsite/api/rest/v1/observations/series

Main byline says: Retrieve series of observations from a specific variable for an entity from the preferred facet.

but it's unclear what "preferred facet" means.

It also seems as if we should allow users to select a facet? /cc @shifucun

**Comment by shifucun** [comment]
This is the simple API where one result is returned. If users want to get other facet, should use the bulk API and select the facet from there.

Also facet id is now only persistent within a request, and is not an official dcid in KG, so we can not make a request param.

**Comment by beets** [comment]
> This is the simple API where one result is returned. If users want to get other facet, should use the bulk API and select the facet from there.
> 
> Also facet id is now only persistent within a request, and is not an official dcid in KG, so we can not make a request param.

Sounds good - this is a departure from our existing API but simplifies things.
