### ISSUE TITLE
Bulk tags show up in page titles

### ISSUE THREAD

**Issue by beets** [datacommonsorg/docsite#280]
We should perhaps add a property to the page (similar to page-order, etc), that can be used in the sidebar generator to add the tag there. Optionally could be used to add the word Bulk to the page title as well.

![image](https://user-images.githubusercontent.com/6052978/202796354-812a0bb3-ae66-4ee2-ae6e-11951cf9b980.png)

**Comment by juliawu** [comment]
Fixed by #282 and #283!
