### ISSUE TITLE
Glossary: Look into the paragraph formatting

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/docsite#69]
https://docs.datacommons.org/contributing/background/glossary.html 

E.g. under Statistical variable, I see some interesting line breakages with indents

**Comment by KilimAnnejaro** [comment]
Hi @tjann, I was formatting the glossary to make it look like https://developers.google.com/style/word-list, which is where the line breaks and indents come from. Is that a good idea or should I be going for something else?

**Comment by tjann** [comment]
This is what I see on our word list:

![image](https://user-images.githubusercontent.com/18621425/93936140-8d2f9f80-fcda-11ea-9804-b7118fbc8182.png)


And on the developer style guide:

![image](https://user-images.githubusercontent.com/18621425/93936192-9fa9d900-fcda-11ea-9928-1de0712cbf50.png)

**Comment by KilimAnnejaro** [comment]
Ohhhh...it isn't responsive. Thanks for letting me know! I'll look into that.
